version: 2

models:
  - name: int_superbowl_ratings
    config:
      contract:
        enforced: true
    columns:
      - name: super_bowl
        data_type: string
      - name: super_bowl_number
        data_type: int64
      - name: date
        data_type: string
        constraints:
          - type: primary_key
        tests:
          - unique
          - not_null
      - name: network
        data_type: string
      - name: average_viewers
        data_type: float
      - name: total_viewers
        data_type: float
      - name: household_rating
        data_type: float
      - name: household_share
        data_type: int64
      - name: cost_of_30_second_ad_usd
        data_type: integer
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: timestamp