version: 2

models:
  - name: int_stadiums
    config:
      contract:
        enforced: true
    columns:
      - name: location
        data_type: string
      - name: address
        data_type: string
      - name: opening_date
        data_type: string
      - name: roof_type
        data_type: string
      - name: capacity
        data_type: int64
      - name: longitude
        data_type: float
      - name: latitude
        data_type: float
      - name: _data_source
        data_type: string
      - name: _load_time
        data_type: timestamp
      - name: universal_stadium_id
        data_type: int64
      - name: stadium_name
        data_type: string
        constraints:
          - type: primary_key
        tests:
         - unique
         - not_null
      - name: review_score
        data_type: float
      - name: superbowls_hosted
        data_type: integer
